{"uid":"348a89ecd394a847","name":"test_precision[Test for QUARTZ]","fullName":"tests.test_network_parameters.TestPrecision#test_precision","historyId":"655d1cc9a50b23cf91af222e92689cfd","time":{"start":1670243150733,"stop":1670243152188,"duration":1455},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","statusTrace":"self = <tests.test_network_parameters.TestPrecision object at 0x7fb8e4db7190>\nchain = <tests.utils.chain_model.Chain object at 0x7fb8e52c8f40>\n\n    def test_precision(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fb8e52c8f40>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","statusTrace":"self = <tests.test_network_parameters.TestPrecision object at 0x7fb8e4db7190>\nchain = <tests.utils.chain_model.Chain object at 0x7fb8e52c8f40>\n\n    def test_precision(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fb8e52c8f40>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"856fa5293942389a","name":"stdout","source":"856fa5293942389a.txt","type":"text/plain","size":216}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestPrecision"},{"name":"host","value":"fv-az424-841"},{"name":"thread","value":"1638-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7fb8e52c8f40>"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"751e7fe8d62e0166","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670243139225,"stop":1670243140716,"duration":1491}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":63,"skipped":0,"passed":239,"unknown":0,"total":302},"items":[{"uid":"441f0fbb3e6eda28","reportUrl":"https://nova-wallet.github.io/test-runner/2026//#testresult/441f0fbb3e6eda28","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670228720715,"stop":1670228722209,"duration":1494}},{"uid":"bc4bb614b9160aaa","reportUrl":"https://nova-wallet.github.io/test-runner/2025//#testresult/bc4bb614b9160aaa","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670214264905,"stop":1670214266030,"duration":1125}},{"uid":"ae8d9cb5a02cce89","reportUrl":"https://nova-wallet.github.io/test-runner/2024//#testresult/ae8d9cb5a02cce89","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670200459846,"stop":1670200460944,"duration":1098}},{"uid":"52a9af500c078202","reportUrl":"https://nova-wallet.github.io/test-runner/2023//#testresult/52a9af500c078202","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670185504461,"stop":1670185506131,"duration":1670}},{"uid":"abd1234987448bc0","reportUrl":"https://nova-wallet.github.io/test-runner/2022//#testresult/abd1234987448bc0","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670171071591,"stop":1670171073113,"duration":1522}},{"uid":"72fa2c025694c473","reportUrl":"https://nova-wallet.github.io/test-runner/2021//#testresult/72fa2c025694c473","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670157926109,"stop":1670157927170,"duration":1061}},{"uid":"7f02c7e5eb9bc413","reportUrl":"https://nova-wallet.github.io/test-runner/2020//#testresult/7f02c7e5eb9bc413","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670143033805,"stop":1670143034688,"duration":883}},{"uid":"8ab98913c88aec9b","reportUrl":"https://nova-wallet.github.io/test-runner/2019//#testresult/8ab98913c88aec9b","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670128620528,"stop":1670128621387,"duration":859}},{"uid":"d08f71da3ead943f","reportUrl":"https://nova-wallet.github.io/test-runner/2018//#testresult/d08f71da3ead943f","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670117348234,"stop":1670117349063,"duration":829}},{"uid":"732b9689282b891d","reportUrl":"https://nova-wallet.github.io/test-runner/2017//#testresult/732b9689282b891d","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670099630482,"stop":1670099631363,"duration":881}},{"uid":"7d8eae3c96943a39","reportUrl":"https://nova-wallet.github.io/test-runner/2016//#testresult/7d8eae3c96943a39","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670085522362,"stop":1670085523678,"duration":1316}},{"uid":"f827d19cbc7fc069","reportUrl":"https://nova-wallet.github.io/test-runner/2015//#testresult/f827d19cbc7fc069","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670071445208,"stop":1670071446085,"duration":877}},{"uid":"7e6028ee89e05bcf","reportUrl":"https://nova-wallet.github.io/test-runner/2014//#testresult/7e6028ee89e05bcf","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670056675404,"stop":1670056676543,"duration":1139}},{"uid":"77dee87c34e67c9c","reportUrl":"https://nova-wallet.github.io/test-runner/2013//#testresult/77dee87c34e67c9c","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670042169748,"stop":1670042170645,"duration":897}},{"uid":"d5cf74c76908088b","reportUrl":"https://nova-wallet.github.io/test-runner/2012//#testresult/d5cf74c76908088b","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670030688862,"stop":1670030689743,"duration":881}},{"uid":"3bf8ea67edbbaf7","reportUrl":"https://nova-wallet.github.io/test-runner/2011//#testresult/3bf8ea67edbbaf7","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1670013297469,"stop":1670013298677,"duration":1208}},{"uid":"ba395834b1fb1e4b","reportUrl":"https://nova-wallet.github.io/test-runner/2010//#testresult/ba395834b1fb1e4b","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1669999188620,"stop":1669999190021,"duration":1401}},{"uid":"532321d3ec8d3e","reportUrl":"https://nova-wallet.github.io/test-runner/2009//#testresult/532321d3ec8d3e","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1669987272189,"stop":1669987273539,"duration":1350}},{"uid":"aa2155fa2371328e","reportUrl":"https://nova-wallet.github.io/test-runner/2000//#testresult/aa2155fa2371328e","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1669884038419,"stop":1669884039719,"duration":1300}},{"uid":"721ccb9256ed2943","reportUrl":"https://nova-wallet.github.io/test-runner/1999//#testresult/721ccb9256ed2943","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","time":{"start":1669869496342,"stop":1669869497236,"duration":894}}]},"tags":[]},"source":"348a89ecd394a847.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7fb8e52c8f40>"]}