{"uid":"dcfa32bb45b36eec","name":"test_precision[Test for Imbue]","fullName":"tests.test_network_parameters.TestPrecision#test_precision","historyId":"74ffc855de20c1e947196ebc92d12f80","time":{"start":1669653421815,"stop":1669653421895,"duration":80},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Imbue","statusTrace":"self = <tests.test_network_parameters.TestPrecision object at 0x7f1630a6d790>\nchain = <tests.utils.chain_model.Chain object at 0x7f1630b52700>\n\n    def test_precision(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7f1630b52700>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Imbue\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Imbue","statusTrace":"self = <tests.test_network_parameters.TestPrecision object at 0x7f1630a6d790>\nchain = <tests.utils.chain_model.Chain object at 0x7f1630b52700>\n\n    def test_precision(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7f1630b52700>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Imbue\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"bd79553e8e62174d","name":"stdout","source":"bd79553e8e62174d.txt","type":"text/plain","size":27}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestPrecision"},{"name":"host","value":"fv-az177-728"},{"name":"thread","value":"1616-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7f1630b52700>"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"dcfa32bb45b36eec.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7f1630b52700>"]}