{"uid":"dbdec68b429f885d","name":"test_chainId[Test for Altair]","fullName":"tests.test_network_parameters.TestChainId#test_chainId","historyId":"1a5d6ea10fff61f48ef875bd6e25e873","time":{"start":1669685008789,"stop":1669685022408,"duration":13619},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","statusTrace":"self = <tests.test_network_parameters.TestChainId object at 0x7fc952faa850>\nchain = <tests.utils.chain_model.Chain object at 0x7fc953487f40>\n\n    def test_chainId(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fc953487f40>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Altair\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","statusTrace":"self = <tests.test_network_parameters.TestChainId object at 0x7fc952faa850>\nchain = <tests.utils.chain_model.Chain object at 0x7fc953487f40>\n\n    def test_chainId(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fc953487f40>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Altair\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"7db1caabbc5efd23","name":"stdout","source":"7db1caabbc5efd23.txt","type":"text/plain","size":162}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestChainId"},{"name":"host","value":"fv-az74-112"},{"name":"thread","value":"1581-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7fc953487f40>"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"d78133fe45079429","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669684984793,"stop":1669684998769,"duration":13976}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":22,"skipped":0,"passed":248,"unknown":0,"total":270},"items":[{"uid":"f80b952ef351e30c","reportUrl":"https://nova-wallet.github.io/test-runner/1985//#testresult/f80b952ef351e30c","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669667151060,"stop":1669667162549,"duration":11489}},{"uid":"c1d7854a9bd23f92","reportUrl":"https://nova-wallet.github.io/test-runner/1984//#testresult/c1d7854a9bd23f92","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669652844475,"stop":1669652857824,"duration":13349}},{"uid":"ebcdaf20676a50e","reportUrl":"https://nova-wallet.github.io/test-runner/1983//#testresult/ebcdaf20676a50e","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669639170945,"stop":1669639185180,"duration":14235}},{"uid":"a81ebb3eabaa785f","reportUrl":"https://nova-wallet.github.io/test-runner/1982//#testresult/a81ebb3eabaa785f","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669624160052,"stop":1669624173271,"duration":13219}},{"uid":"f83a67d3ca80bb48","reportUrl":"https://nova-wallet.github.io/test-runner/1981//#testresult/f83a67d3ca80bb48","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669609704095,"stop":1669609717469,"duration":13374}},{"uid":"50815b177240d8ba","reportUrl":"https://nova-wallet.github.io/test-runner/1980//#testresult/50815b177240d8ba","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669598416317,"stop":1669598429496,"duration":13179}},{"uid":"9b40cbc0770ae512","reportUrl":"https://nova-wallet.github.io/test-runner/1979//#testresult/9b40cbc0770ae512","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669580701155,"stop":1669580712634,"duration":11479}},{"uid":"76490f3a3f4ebd5d","reportUrl":"https://nova-wallet.github.io/test-runner/1978//#testresult/76490f3a3f4ebd5d","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669566647623,"stop":1669566662308,"duration":14685}},{"uid":"4ade308d65869da4","reportUrl":"https://nova-wallet.github.io/test-runner/1977//#testresult/4ade308d65869da4","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669552542330,"stop":1669552555952,"duration":13622}},{"uid":"e1fac2ef1b9ef7ff","reportUrl":"https://nova-wallet.github.io/test-runner/1976//#testresult/e1fac2ef1b9ef7ff","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669537682311,"stop":1669537695844,"duration":13533}},{"uid":"a8f8ae24caba922c","reportUrl":"https://nova-wallet.github.io/test-runner/1975//#testresult/a8f8ae24caba922c","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669523275708,"stop":1669523289299,"duration":13591}},{"uid":"482870d1fc3a1794","reportUrl":"https://nova-wallet.github.io/test-runner/1973//#testresult/482870d1fc3a1794","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669493693478,"stop":1669493705942,"duration":12464}},{"uid":"618e9ac31a24487f","reportUrl":"https://nova-wallet.github.io/test-runner/1972//#testresult/618e9ac31a24487f","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669479311390,"stop":1669479325112,"duration":13722}},{"uid":"6a56eedac8b920f3","reportUrl":"https://nova-wallet.github.io/test-runner/1971//#testresult/6a56eedac8b920f3","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669464930830,"stop":1669464944970,"duration":14140}},{"uid":"a6f7529bfa5b668d","reportUrl":"https://nova-wallet.github.io/test-runner/1970//#testresult/a6f7529bfa5b668d","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669450510702,"stop":1669450524269,"duration":13567}},{"uid":"d8da90e96e87a415","reportUrl":"https://nova-wallet.github.io/test-runner/1969//#testresult/d8da90e96e87a415","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669436122635,"stop":1669436136604,"duration":13969}},{"uid":"88c6f09cc3874511","reportUrl":"https://nova-wallet.github.io/test-runner/1968//#testresult/88c6f09cc3874511","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669422211691,"stop":1669422224887,"duration":13196}},{"uid":"aee833d865238506","reportUrl":"https://nova-wallet.github.io/test-runner/1967//#testresult/aee833d865238506","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669407284817,"stop":1669407298415,"duration":13598}},{"uid":"c53d141567569c0c","reportUrl":"https://nova-wallet.github.io/test-runner/1966//#testresult/c53d141567569c0c","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669392891313,"stop":1669392904921,"duration":13608}},{"uid":"d911c77bfba0d7fc","reportUrl":"https://nova-wallet.github.io/test-runner/1965//#testresult/d911c77bfba0d7fc","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Altair","time":{"start":1669378542331,"stop":1669378555640,"duration":13309}}]},"tags":[]},"source":"dbdec68b429f885d.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7fc953487f40>"]}