{"uid":"bd9d91240c14716","name":"test_address_prefix[Test for Zeitgeist]","fullName":"tests.test_network_parameters.TestNetworkPrefix#test_address_prefix","historyId":"92c81a144bf4039302f205ea20d7374c","time":{"start":1669725107910,"stop":1669725108808,"duration":898},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Zeitgeist","statusTrace":"self = <tests.test_network_parameters.TestNetworkPrefix object at 0x7fabecda79d0>\nchain = <tests.utils.chain_model.Chain object at 0x7fabece06280>\n\n    def test_address_prefix(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fabece06280>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Zeitgeist\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Zeitgeist","statusTrace":"self = <tests.test_network_parameters.TestNetworkPrefix object at 0x7fabecda79d0>\nchain = <tests.utils.chain_model.Chain object at 0x7fabece06280>\n\n    def test_address_prefix(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fabece06280>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Zeitgeist\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"e7a5cebb3ec8539b","name":"stdout","source":"e7a5cebb3ec8539b.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestNetworkPrefix"},{"name":"host","value":"fv-az304-876"},{"name":"thread","value":"1621-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7fabece06280>"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"bd9d91240c14716.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7fabece06280>"]}