{"uid":"b446a1f3b1b4953c","name":"test_precision[Test for QUARTZ]","fullName":"tests.test_network_parameters.TestPrecision#test_precision","historyId":"655d1cc9a50b23cf91af222e92689cfd","time":{"start":1670013286262,"stop":1670013287461,"duration":1199},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","statusTrace":"self = <tests.test_network_parameters.TestPrecision object at 0x7f90e282f220>\nchain = <tests.utils.chain_model.Chain object at 0x7f90e28b9070>\n\n    def test_precision(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7f90e28b9070>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","statusTrace":"self = <tests.test_network_parameters.TestPrecision object at 0x7f90e282f220>\nchain = <tests.utils.chain_model.Chain object at 0x7f90e28b9070>\n\n    def test_precision(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7f90e28b9070>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"259a35c4c3f325c0","name":"stdout","source":"259a35c4c3f325c0.txt","type":"text/plain","size":108}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestPrecision"},{"name":"host","value":"fv-az459-905"},{"name":"thread","value":"1858-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7f90e28b9070>"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"b446a1f3b1b4953c.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7f90e28b9070>"]}