{"uid":"97332b47a8e7c393","name":"test_precision[Test for XX network]","fullName":"tests.test_network_parameters.TestPrecision#test_precision","historyId":"e555e4a1ce87171c73257fbc649e4460","time":{"start":1669610336298,"stop":1669610337079,"duration":781},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] XX network","statusTrace":"self = <tests.test_network_parameters.TestPrecision object at 0x7fa103e49e20>\nchain = <tests.utils.chain_model.Chain object at 0x7fa103f2f9a0>\n\n    def test_precision(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fa103f2f9a0>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] XX network\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] XX network","statusTrace":"self = <tests.test_network_parameters.TestPrecision object at 0x7fa103e49e20>\nchain = <tests.utils.chain_model.Chain object at 0x7fa103f2f9a0>\n\n    def test_precision(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fa103f2f9a0>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] XX network\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"7803a2530b6968dc","name":"stdout","source":"7803a2530b6968dc.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestPrecision"},{"name":"host","value":"fv-az550-315"},{"name":"thread","value":"1684-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7fa103f2f9a0>"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"97332b47a8e7c393.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7fa103f2f9a0>"]}